--Création de la base de donnée
CREATE DATABASE ACFG_LaboGSB

--Création de la table VISITEUR
CREATE TABLE VISITEUR (
 VIS_ID INT IDENTITY (1,1),
 VIS_PRENOM VARCHAR(38),
 VIS_NOM VARCHAR(38),
 VIS_MDP VARCHAR(1000),
 VIS_LOGIN CHAR(4),
 CONSTRAINT PK_VISITEUR_ID PRIMARY KEY (VIS_ID)
)

--Insertion Table VISITEUR
INSERT INTO VISITEUR (VIS_PRENOM, VIS_NOM, VIS_MDP, VIS_LOGIN)
VALUES ('Sebastien', 'AUBERT', 'sebaub273', 'sAUB')

--Test
SELECT * FROM VISITEUR

DELETE FROM VISITEUR


--Création de la procédure Login Validation
CREATE PROC PS_LOGIN_VALIDATION
	@Login CHAR(4),
	@Mdp VARCHAR(512)
AS
	SELECT VIS_ID
	FROM VISITEUR
	WHERE VIS_LOGIN = @Login
	AND VIS_MDP = @Mdp

DROP PROC PS_LOGIN_VALIDATION
exec PS_LOGIN_VALIDATION 'sAUB', '07BD1F429D552A998C922ED3CFC94A974EA27E29DADFD0CDD06748BE9E9F1C08DF6FAE41C2322E0527F430046EF4053779A47A9708986D0D4C12D363F4EDF902'

--Création du trigger pour Hasher le mdp en SHA512 en base
CREATE TRIGGER TRI_HASHAGE
ON VISITEUR
INSTEAD OF INSERT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @MDPHASH VARCHAR(500)
	
	SELECT @MDPHASH = CONVERT(NVARCHAR(512),HashBytes('SHA2_512', VIS_MDP),2) FROM inserted 

	  INSERT dbo.VISITEUR(VIS_PRENOM, VIS_NOM, VIS_LOGIN, VIS_MDP)
		SELECT VIS_PRENOM, VIS_NOM, VIS_LOGIN, @MDPHASH
		FROM inserted;

END

DROP TRIGGER TRI_HASHAGE


